version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: api-secret-message
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/api-secret-message/dist
      - ./package.json:/usr/src/api-secret-message/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
